### ISSUE TITLE
Only shows packages whose names start with [A-C]

### ISSUE THREAD

**Issue by traktofon** [djsegal/julia_observer#48] opened 2017-06-16 03:54 UTC
At the moment the [list of packages](https://juliaobserver.com/packages) appears to have been severely truncated, e.g. the alphabetical sort only shows 7 pages with last package being CVXOPT. Also, searching by name (e.g. for PyPlot) doesn't find the missing packages.

**Comment by djsegal** [comment] 2017-06-17 00:57
Outage was caused by problem fixed in: https://github.com/djsegal/julia_observer/commit/f3c1e9dbf3d46a514f5b2e0fcad5c568ef870e68 // i.e. got a broken api request from github

Thanks for the heads up!

**Closed by djsegal** 2017-06-17 00:57 UTC
